In [1]:
print("Hello World")

Hello World

## Date:- 2026-04-25

In [36]:
import pandas as pd
import numpy as np
FILE = "csv-2/copy.csv"
df = pd.read_csv(FILE)

In [37]:
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,0,36
1,40,69517,781,1,1,0,0,36
2,49,28572,568,2,0,0,83408,36
3,60,71067,654,1,1,1,0,36
4,39,68930,767,1,1,0,0,36

## Assigning loan to UN Employed

In [21]:
## POOR Cibil

poor_unemp = (df['employed'] == 0) & (df['credit_score'].between(401, 550))

In [23]:


df.loc[(poor_unemp) & (df['age'].between(25, 29)), 'loan_amount'] = \
    np.random.randint(40000, 70000, size=df[(poor_unemp) & (df['age'].between(25, 29))].shape[0])

df.loc[(poor_unemp) & (df['age'].between(30, 40)), 'loan_amount'] = \
    np.random.randint(50000, 100000, size=df[(poor_unemp) & (df['age'].between(30, 40))].shape[0])

df.loc[(poor_unemp) & (df['age'].between(41, 55)), 'loan_amount'] = \
    np.random.randint(70000, 100000, size=df[(poor_unemp) & (df['age'].between(41, 55))].shape[0])

df.loc[(poor_unemp) & (df['age'].between(56, 59)), 'loan_amount'] = \
    np.random.randint(50000, 80000, size=df[(poor_unemp) & (df['age'].between(56, 59))].shape[0])

df.loc[(poor_unemp) & (df['age'] >= 60), 'loan_amount'] = \
    np.random.randint(40000, 70000, size=df[(poor_unemp) & (df['age'] >= 60)].shape[0])

print(f"Unemployed poor credit loans assigned! {poor_unemp.sum()} rows")

Unemployed poor credit loans assigned! 23 rows

In [38]:
df[poor_unemp]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
105,46,29031,471,1,0,1,79289,36
387,64,9529,536,3,0,1,46594,36
991,25,14532,513,0,0,0,66284,36
1503,41,26824,537,3,0,0,94573,36
1573,25,12436,539,1,0,0,65062,36
1602,34,19750,511,1,0,1,71039,36
1632,34,23722,550,0,0,0,91877,36
1779,33,18663,541,2,0,1,81430,36
1795,32,19588,476,1,0,1,98025,36
1975,37,26400,533,3,0,1,62620,36
2012,32,24078,548,1,0,0,82264,36
2135,35,23778,504,3,0,1,90250,36
2154,26,16023,546,0,0,0,60623,36
2567,49,29944,548,2,0,1,78102,36
2970,25,11332,519,1,0,1,40962,36
3285,60,12210,495,2,0,1,58190,36
3498,39,26180,548,3,0,1,75354,36
3828,56,20476,500,3,0,1,78838,36
3879,39,26816,547,0,0,0,99414,36
4163,25,16997,536,0,0,0,40513,36
4500,30,16542,545,1,0,1,78705,36
4529,35,21985,550,1,0,0,73102,36
4747,28,11446,513,0,0,0,41494,36

In [15]:
df.loc[
    (df["loan_amount"]>0)
]

Empty DataFrame
Columns: [age, income, credit_score, existing_loans, employed, default, loan_amount, loan_tenure_months]
Index: []

In [25]:
# GOOD CIBIL 

good_unemp = (df['employed'] == 0) & (df['credit_score'].between(551, 699))

In [27]:

df.loc[(good_unemp) & (df['age'].between(25, 29)), 'loan_amount'] = \
    np.random.randint(50000, 90000, size=df[(good_unemp) & (df['age'].between(25, 29))].shape[0])

df.loc[(good_unemp) & (df['age'].between(30, 40)), 'loan_amount'] = \
    np.random.randint(60000, 120000, size=df[(good_unemp) & (df['age'].between(30, 40))].shape[0])

df.loc[(good_unemp) & (df['age'].between(41, 55)), 'loan_amount'] = \
    np.random.randint(80000, 130000, size=df[(good_unemp) & (df['age'].between(41, 55))].shape[0])

df.loc[(good_unemp) & (df['age'].between(56, 59)), 'loan_amount'] = \
    np.random.randint(70000, 110000, size=df[(good_unemp) & (df['age'].between(56, 59))].shape[0])

df.loc[(good_unemp) & (df['age'] >= 60), 'loan_amount'] = \
    np.random.randint(50000, 90000, size=df[(good_unemp) & (df['age'] >= 60)].shape[0])

print(f"Unemployed good credit loans assigned! {good_unemp.sum()} rows")

Unemployed good credit loans assigned! 347 rows

In [39]:

df[good_unemp]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
2,49,28572,568,2,0,0,83408,36
65,58,20213,626,3,0,0,97036,36
67,54,29050,653,0,0,0,86095,36
75,51,28178,662,0,0,0,124134,36
115,45,27814,647,2,0,0,106901,36
...,...,...,...,...,...,...,...,...
4958,41,27814,618,1,0,0,110722,36
4970,60,8412,696,1,0,0,53885,36
4973,25,17576,688,0,0,0,81729,36
4976,58,21553,695,2,0,1,94476,36
4987,42,27657,694,4,0,1,106236,36

In [29]:
# BEST cibil

best_unemp = (df['employed'] == 0) & (df['credit_score'] >= 700)

In [31]:


df.loc[(best_unemp) & (df['age'].between(25, 29)), 'loan_amount'] = \
    np.random.randint(40000, 80000, size=df[(best_unemp) & (df['age'].between(25, 29))].shape[0])

df.loc[(best_unemp) & (df['age'].between(30, 40)), 'loan_amount'] = \
    np.random.randint(60000, 110000, size=df[(best_unemp) & (df['age'].between(30, 40))].shape[0])

df.loc[(best_unemp) & (df['age'].between(41, 55)), 'loan_amount'] = \
    np.random.randint(80000, 150000, size=df[(best_unemp) & (df['age'].between(41, 55))].shape[0])

df.loc[(best_unemp) & (df['age'].between(56, 59)), 'loan_amount'] = \
    np.random.randint(70000, 130000, size=df[(best_unemp) & (df['age'].between(56, 59))].shape[0])

df.loc[(best_unemp) & (df['age'] >= 60), 'loan_amount'] = \
    np.random.randint(70000, 110000, size=df[(best_unemp) & (df['age'] >= 60)].shape[0])

print(f"Unemployed best credit loans assigned! {best_unemp.sum()} rows")

Unemployed best credit loans assigned! 348 rows

In [40]:
df[best_unemp]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
30,34,15798,763,1,0,1,74613,36
83,35,17965,724,0,0,0,99329,36
95,25,14191,770,1,0,1,67635,36
103,32,16416,817,3,0,0,73468,36
106,64,13086,738,1,0,0,97949,36
...,...,...,...,...,...,...,...,...
4896,25,16605,773,1,0,0,57143,36
4911,57,21696,799,4,0,1,127077,36
4912,51,29587,831,2,0,1,95505,36
4961,29,11272,746,3,0,1,48500,36
4993,48,29448,723,3,0,1,99515,36

In [41]:
df.loc[
    (df["employed"]==0) &
    (df["loan_amount"]>0)
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
2,49,28572,568,2,0,0,83408,36
30,34,15798,763,1,0,1,74613,36
65,58,20213,626,3,0,0,97036,36
67,54,29050,653,0,0,0,86095,36
75,51,28178,662,0,0,0,124134,36
...,...,...,...,...,...,...,...,...
4970,60,8412,696,1,0,0,53885,36
4973,25,17576,688,0,0,0,81729,36
4976,58,21553,695,2,0,1,94476,36
4987,42,27657,694,4,0,1,106236,36
4993,48,29448,723,3,0,1,99515,36

In [35]:
# Safe point

df.to_csv(FILE, index=False)