In [1]:
print("Hello World")

Hello World

In [2]:
import pandas as pd
import numpy as np

In [3]:
FILE_PATH = "csv/copy.csv"

## Date :- 2026-04-20

In [4]:
df = pd.read_csv(FILE_PATH)

In [5]:
df.head()

   age  income  credit_score  existing_loans  employed  default
0   47  151735           616               1         1        0
1   40   72912           781               1         1        0
2   49  152455           568               2         0        0
3   60  120771           654               1         1        1
4   39   86572           767               1         1        0

In [12]:
mask = (df["existing_loans"]<1, "default")
df.loc[mask]

35      0
43      0
46      0
63      0
67      0
       ..
4957    0
4959    0
4966    0
4973    0
4998    0
Name: default, Length: 657, dtype: int64

In [13]:
df.loc[
    (df["existing_loans"]==0) &
    (df["default"]>0)
]

Empty DataFrame
Columns: [age, income, credit_score, existing_loans, employed, default]
Index: []