In [1]:
print("Hello World")

Hello World

In [2]:
import pandas as pd
import numpy as np

In [3]:
FILE_PATH = "csv/copy.csv"

## Date :- 2026-04-20

In [61]:
df = pd.read_csv(FILE_PATH)

In [62]:
df.head()

   age  income  credit_score  existing_loans  employed  default
0   47  151735           616               1         1        0
1   40   72912           781               1         1        0
2   49  152455           568               2         0        0
3   60  120771           654               1         1        1
4   39   86572           767               1         1        0

In [12]:
mask = (df["existing_loans"]<1, "default")
df.loc[mask]

35      0
43      0
46      0
63      0
67      0
       ..
4957    0
4959    0
4966    0
4973    0
4998    0
Name: default, Length: 657, dtype: int64

In [63]:
df.loc[
    (df["existing_loans"]==0) &
    (df["default"]>0)
]

Empty DataFrame
Columns: [age, income, credit_score, existing_loans, employed, default]
Index: []

In [64]:
df["loan_amount"] = 0

In [31]:
df.rename(columns={"loan":"loan_amount"}, inplace=True)

In [65]:
tier1 = (df["employed"]==0) & \
(df["credit_score"]<550) & \
(df["age"]<30)

In [66]:
df.loc[tier1]

,age,income,credit_score,existing_loans,employed,default,loan_amount
991,25,4716,513,0,0,0,0
1573,25,3070,539,1,0,0,0
2154,26,4500,546,0,0,0,0
2970,25,3973,519,1,0,1,0
4163,25,3149,536,0,0,0,0
4747,28,4928,513,0,0,0,0

In [67]:
df["loan_tenure_months"] = 36

In [68]:
loan_multiplier = df.loc[tier1, "income"]*2

In [69]:
l = loan_multiplier*np.round(np.random.uniform(0.95, 1.1, size=df[tier1].shape[0]))

In [70]:
df.loc[tier1, "loan_amount"] = l

In [71]:
df.loc[tier1]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
991,25,4716,513,0,0,0,9432,36
1573,25,3070,539,1,0,0,6140,36
2154,26,4500,546,0,0,0,9000,36
2970,25,3973,519,1,0,1,7946,36
4163,25,3149,536,0,0,0,6298,36
4747,28,4928,513,0,0,0,9856,36