In [1]:
print("Hello World")

Hello World

In [1]:
import pandas as pd
import numpy as np
FILE = "csv-2/copy.csv"
df = pd.read_csv(FILE)

In [2]:
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,0,36
1,40,69517,781,1,1,0,0,36
2,49,28572,568,2,0,0,0,36
3,60,71067,654,1,1,1,0,36
4,39,68930,767,1,1,0,0,36

In [ ]:
df

# Employed

In [44]:
import numpy as np

# Filter: Employed (1) aur Age 25-28
mask = (df["employed"] == 1) & (df["age"].between(25, 28))

# Income assign karo (55% → 20-28k, 45% → 28-35k)
df.loc[mask, "income"] = df.loc[mask].apply(
    lambda row: np.random.randint(20000, 28000) if np.random.random() < 0.55 
                else np.random.randint(28000, 35000),
    axis=1
)

In [45]:
df[mask]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
13,25,22930,734,1,1,1,0,36
14,25,23095,801,3,1,0,0,36
19,25,22375,721,5,1,1,0,36
23,25,21139,676,2,1,0,0,36
26,28,24001,697,1,1,1,0,36
...,...,...,...,...,...,...,...,...
4974,25,23691,559,5,1,0,0,36
4975,25,26154,769,1,1,0,0,36
4979,25,27693,632,2,1,0,0,36
4980,27,20531,666,2,1,0,0,36
4990,25,30843,667,2,1,0,0,36

In [46]:
import numpy as np

# Filter: Employed (1) aur Age 29-30
mask = (df["employed"] == 1) & (df["age"].between(29, 30))

# Income assign karo (33k-40k)
df.loc[mask, "income"] = df.loc[mask].apply(
    lambda row: np.random.randint(33000, 40000),
    axis=1
)

In [47]:
mask = (df["employed"] == 1) & (df["age"].between(29, 30))
df[mask]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
16,29,39764,652,2,1,0,0,36
33,29,39246,577,1,1,0,0,36
126,30,33615,634,3,1,0,0,36
132,29,35724,728,0,1,0,0,36
134,30,37331,564,3,1,1,0,36
...,...,...,...,...,...,...,...,...
4894,29,38477,655,1,1,0,0,36
4901,29,37864,801,2,1,0,0,36
4902,29,35744,645,2,1,0,0,36
4966,30,35584,712,0,1,0,0,36
4972,29,36366,696,3,1,1,0,36

In [51]:
import numpy as np

# Filter: Employed (1) aur Age 31-35
mask = (df["employed"] == 1) & (df["age"].between(31, 35))

# Income assign karo (40k-55k)
df.loc[mask, "income"] = df.loc[mask].apply(
    lambda row: np.random.randint(45000, 63000),
    axis=1
)

In [54]:
mask = (df["employed"] == 1) & (df["age"].between(31, 35))
df[mask]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
15,35,61122,734,3,1,0,0,36
18,31,56305,647,3,1,0,0,36
24,35,49676,787,1,1,0,0,36
28,34,55345,738,3,1,1,0,36
45,33,56291,807,3,1,0,0,36
...,...,...,...,...,...,...,...,...
4943,33,59246,720,4,1,1,0,36
4946,33,48434,625,0,1,0,0,36
4964,34,62168,607,5,1,1,0,36
4994,34,50808,839,1,1,0,0,36
4999,31,48188,674,1,1,0,0,36

In [55]:
import numpy as np

# Filter: Employed (1) aur Age 36-45
mask = (df["employed"] == 1) & (df["age"].between(36, 45))

# Income assign karo (65% → 65-70k, 35% → 70-85k)
df.loc[mask, "income"] = df.loc[mask].apply(
    lambda row: np.random.randint(65000, 70000) if np.random.random() < 0.65 
                else np.random.randint(70000, 85000),
    axis=1
)

In [58]:
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,146046,616,1,1,0,0,36
1,40,69517,781,1,1,0,0,36
2,49,28572,568,2,0,0,0,36
3,60,72556,654,1,1,1,0,36
4,39,68930,767,1,1,0,0,36

In [57]:
mask = (df["employed"] == 1) & (df["age"].between(36, 45))
df[mask]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
1,40,69517,781,1,1,0,0,36
4,39,68930,767,1,1,0,0,36
5,39,67947,695,1,1,0,0,36
8,36,68281,674,1,1,0,0,36
10,36,76048,609,2,1,0,0,36
...,...,...,...,...,...,...,...,...
4983,40,66657,568,1,1,1,0,36
4986,39,69338,697,1,1,0,0,36
4988,44,79192,607,1,1,0,0,36
4992,40,84042,693,1,1,1,0,36
4995,41,69736,745,2,1,0,0,36

In [59]:
import numpy as np

# Filter: Employed (1) aur Age 46-55
mask = (df["employed"] == 1) & (df["age"].between(46, 55))

# Income assign karo (50% → 100-120k, 50% → 120-150k)
df.loc[mask, "income"] = df.loc[mask].apply(
    lambda row: np.random.randint(100000, 120000) if np.random.random() < 0.50 
                else np.random.randint(140000, 180000),
    axis=1
)

In [61]:
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,0,36
1,40,69517,781,1,1,0,0,36
2,49,28572,568,2,0,0,0,36
3,60,72556,654,1,1,1,0,36
4,39,68930,767,1,1,0,0,36

In [62]:
mask = (df["employed"] == 1) & (df["age"].between(46, 55))
df[mask]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,0,36
7,51,117736,537,4,1,0,0,36
9,48,149422,806,2,1,0,0,36
27,46,175176,749,2,1,1,0,36
34,51,110233,672,1,1,0,0,36
...,...,...,...,...,...,...,...,...
4981,52,103093,708,1,1,0,0,36
4984,48,119424,555,1,1,0,0,36
4991,50,152453,651,1,1,0,0,36
4996,50,103089,768,3,1,0,0,36
4998,51,166975,638,0,1,0,0,36

In [63]:
import numpy as np

# Filter: Employed (1) aur Age 56-59
mask = (df["employed"] == 1) & (df["age"].between(56, 59))

# Income assign karo (55% → 90-110k, 45% → 110-140k)
df.loc[mask, "income"] = df.loc[mask].apply(
    lambda row: np.random.randint(100000, 110000) if np.random.random() < 0.55 
                else np.random.randint(110000, 140000),
    axis=1
)

In [64]:
mask = (df["employed"] == 1) & (df["age"].between(56, 59))
df[mask]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
20,59,100762,599,2,1,0,0,36
82,59,104928,668,3,1,1,0,36
122,58,122838,770,5,1,0,0,36
141,57,108845,807,3,1,0,0,36
177,59,132039,660,5,1,1,0,36
...,...,...,...,...,...,...,...,...
4918,58,111787,719,3,1,0,0,36
4919,57,137525,557,1,1,0,0,36
4937,56,123850,776,2,1,0,0,36
4951,57,108581,692,1,1,0,0,36
4969,59,102129,635,1,1,0,0,36

In [65]:
import numpy as np

# Filter: Employed (1) aur Age 60+
mask = (df["employed"] == 1) & (df["age"] >= 60)

# Income assign karo (60% → 60-75k, 40% → 75-100k)
df.loc[mask, "income"] = df.loc[mask].apply(
    lambda row: np.random.randint(70000, 75000) if np.random.random() < 0.60 
                else np.random.randint(80000, 100000),
    axis=1
)

In [66]:
mask = (df["employed"] == 1) & (df["age"] >= 60)
df[mask]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
3,60,71067,654,1,1,1,0,36
6,60,73017,790,1,1,0,0,36
31,64,95509,680,5,1,0,0,36
71,60,88864,770,1,1,0,0,36
73,60,74991,789,3,1,0,0,36
...,...,...,...,...,...,...,...,...
4932,60,90634,700,1,1,0,0,36
4944,62,70087,581,0,1,0,0,36
4985,61,73889,735,2,1,0,0,36
4989,70,74306,698,1,1,0,0,36
4997,70,89423,788,2,1,0,0,36

In [67]:
df.loc[
    (df["income"]>0)
].shape

(5000, 8)

In [68]:
df.to_csv(FILE, index=False)

In [71]:
df = pd.read_csv(FILE)

In [72]:
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,0,36
1,40,69517,781,1,1,0,0,36
2,49,28572,568,2,0,0,0,36
3,60,71067,654,1,1,1,0,36
4,39,68930,767,1,1,0,0,36