In [1]:
print("Hello World")

Hello World

In [2]:
import pandas as pd
import numpy as np

In [3]:
FILE_PATH = "csv/copy.csv"

## Date :- 2026-04-20

In [4]:
df = pd.read_csv(FILE_PATH)

In [5]:
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,151735,616,1,1,0,0,36
1,40,72912,781,1,1,0,0,36
2,49,152455,568,2,0,0,0,36
3,60,120771,654,1,1,1,0,36
4,39,86572,767,1,1,0,0,36

In [6]:
mask = (df["existing_loans"]<1, "default")
df.loc[mask]

35      0
43      0
46      0
63      0
67      0
       ..
4957    0
4959    0
4966    0
4973    0
4998    0
Name: default, Length: 657, dtype: int64

In [7]:
df.loc[
    (df["existing_loans"]==0) &
    (df["default"]>0)
]

Empty DataFrame
Columns: [age, income, credit_score, existing_loans, employed, default, loan_amount, loan_tenure_months]
Index: []

In [8]:
df["loan_amount"] = 0

In [9]:
df.rename(columns={"loan":"loan_amount"}, inplace=True)

In [10]:
tier1 = (df["employed"]==0) & \
(df["credit_score"]<550) & \
(df["age"]<30)

In [11]:
df.loc[tier1]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
991,25,4716,513,0,0,0,0,36
1573,25,3070,539,1,0,0,0,36
2154,26,4500,546,0,0,0,0,36
2970,25,3973,519,1,0,1,0,36
4163,25,3149,536,0,0,0,0,36
4747,28,4928,513,0,0,0,0,36

In [12]:
df["loan_tenure_months"] = 36

In [13]:
loan_multiplier = df.loc[tier1, "income"]*2

In [14]:
l = loan_multiplier*np.round(np.random.uniform(0.95, 1.1, size=df[tier1].shape[0]))

In [15]:
df.loc[tier1, "loan_amount"] = l

In [16]:
df.loc[tier1]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
991,25,4716,513,0,0,0,9432,36
1573,25,3070,539,1,0,0,6140,36
2154,26,4500,546,0,0,0,9000,36
2970,25,3973,519,1,0,1,7946,36
4163,25,3149,536,0,0,0,6298,36
4747,28,4928,513,0,0,0,9856,36

## TIER 2

In [29]:
tier2 = (df["employed"]==0) & \
    (df["credit_score"].between(551, 750)) & \
    (df["age"]>=50) & \
    (df["existing_loans"].between(0, 2))

In [37]:
df.loc[
    (df["employed"]==0) &
    (df["credit_score"].between(551, 750)) &
    (df["age"]>=50) & 
    (df["existing_loans"].between(0, 2))
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
67,54,15926,653,0,0,0,111482,36
75,51,17187,662,0,0,0,120309,36
106,64,8737,738,1,0,0,61159,36
118,55,8336,680,2,0,1,58352,36
135,60,14495,708,0,0,0,101465,36
...,...,...,...,...,...,...,...,...
4857,53,15705,707,2,0,0,109935,36
4905,53,15661,685,0,0,0,109627,36
4923,58,11475,656,1,0,0,80325,36
4970,60,16573,696,1,0,0,116011,36
4976,58,15020,695,2,0,1,105140,36

In [19]:
df.loc[tier2].shape

(82, 8)

In [20]:
# # High previous earners → high pension
# df.loc[(tier2) & (df['income'] > 100000), 'income'] = np.random.randint(15000, 20000, size=46)

# df.loc[(tier2) & (df['income'].between(50000, 100000)), 'income'] = np.random.randint(8000, 15000, size=35)

# df.loc[(tier2) & (df['income'] < 50000), 'income'] = 6000

In [21]:
df.loc[(tier2) & (df['income'] > 100000)]

Empty DataFrame
Columns: [age, income, credit_score, existing_loans, employed, default, loan_amount, loan_tenure_months]
Index: []

In [22]:
df.loc[(tier2) & (df['income'].between(50000, 100000)), "income"] = np.random.randint(8000, 15000, size=35)

ValueError: Must have equal len keys and value when setting with an iterable

In [ ]:
df.loc[(tier2) & (df['income'] < 50000), "income"] = 6000

In [ ]:
df.loc[(tier2) & (df['income'].between(8000, 15000)) ]

In [ ]:
df.loc[(tier2) & (df['income'] > 100000), 'income'] = np.random.randint(15000, 20000, size=46)

In [ ]:
df.loc[(tier2) & (df['income'] > 15000)]

In [ ]:
df.to_csv(FILE_PATH, index=False)

In [ ]:
df = pd.read_csv(FILE_PATH)

In [ ]:
df.loc[tier2, 'loan_amount'] = df.loc[tier2, 'income'] * 7 * np.round(np.random.uniform(0.9, 1.1, size=tier2.sum()))

In [ ]:
df.loc[tier2]

In [ ]:
df.to_csv(FILE_PATH, index=False)

## Date:- 2026-04-21

In [23]:
import pandas as pd
import numpy as np

In [24]:
FILE_PATH = "csv/copy.csv"

In [25]:
df = pd.read_csv(FILE_PATH)

In [26]:
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,151735,616,1,1,0,0,36
1,40,72912,781,1,1,0,0,36
2,49,152455,568,2,0,0,0,36
3,60,120771,654,1,1,1,0,36
4,39,86572,767,1,1,0,0,36

In [38]:
df.loc[tier2]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
67,54,15926,653,0,0,0,111482,36
75,51,17187,662,0,0,0,120309,36
106,64,8737,738,1,0,0,61159,36
118,55,8336,680,2,0,1,58352,36
135,60,14495,708,0,0,0,101465,36
...,...,...,...,...,...,...,...,...
4857,53,15705,707,2,0,0,109935,36
4905,53,15661,685,0,0,0,109627,36
4923,58,11475,656,1,0,0,80325,36
4970,60,16573,696,1,0,0,116011,36
4976,58,15020,695,2,0,1,105140,36

In [40]:
df.head(2)

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,151735,616,1,1,0,0,36
1,40,72912,781,1,1,0,0,36

## Tier 3

In [41]:
tier3 = (df["employed"]==1) & \
(df["credit_score"]<550) & \
(df["age"]<35) & \
(df["income"]<=50000) & \
(df["existing_loans"].between(0, 2))

In [44]:
df.loc[tier3]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
382,25,20597,493,1,1,0,0,36
1561,33,49116,375,1,1,0,0,36
1763,25,37158,539,0,1,0,0,36
2344,25,46616,548,0,1,0,0,36
3454,25,24791,481,2,1,1,0,36
3861,32,46206,537,2,1,1,0,36
4219,25,26060,540,2,1,0,0,36
4478,25,24131,548,2,1,0,0,36
4498,25,25024,540,1,1,0,0,36

In [46]:
df[tier3].shape

(9, 8)

In [48]:
# Sab ko 3x multiplier + randomness
df.loc[tier3, 'loan_amount'] = df.loc[tier3, 'income'] * 3 * \
                                np.round(np.random.uniform(0.9, 1.1, size=df[tier3].shape[0]))

In [49]:
df.loc[tier3]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
382,25,20597,493,1,1,0,61791.0,36
1561,33,49116,375,1,1,0,147348.0,36
1763,25,37158,539,0,1,0,111474.0,36
2344,25,46616,548,0,1,0,139848.0,36
3454,25,24791,481,2,1,1,74373.0,36
3861,32,46206,537,2,1,1,138618.0,36
4219,25,26060,540,2,1,0,78180.0,36
4478,25,24131,548,2,1,0,72393.0,36
4498,25,25024,540,1,1,0,75072.0,36

In [60]:
d = df.loc[
    (df["loan_amount"]==0)
]

In [61]:
d.shape

(4903, 8)

## Tier 4

In [96]:
tier4 = (df['employed'] == 1) & \
        (df['credit_score'] < 550) & \
        (df['age'] >= 50) & \
        (df['income'] >= 100000) & \
        (df['existing_loans'].between(0, 3))

In [97]:
df.loc[tier4, 'loan_amount'] = df.loc[tier4, 'income'] * 5 * \
                                np.round(np.random.uniform(0.9, 1.1, size=df[tier4].shape[0]))

In [98]:
df.loc[tier4, 'loan_amount'] = df.loc[tier4, 'loan_amount'].astype(int)

In [99]:
df[tier4]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
202,54,101514,484,2,1,0,507570.0,36
500,53,124327,531,1,1,0,621635.0,36
707,63,152150,549,1,1,0,760750.0,36
928,60,142153,541,3,1,0,710765.0,36
1010,57,102784,530,0,1,0,513920.0,36
1161,69,158341,467,1,1,0,791705.0,36
1296,53,114860,545,1,1,1,574300.0,36
1507,53,105184,399,3,1,1,525920.0,36
1615,70,197620,513,3,1,1,988100.0,36
1627,57,126038,520,1,1,0,630190.0,36
1854,54,157472,520,1,1,0,787360.0,36
2235,50,116333,543,3,1,0,581665.0,36
2249,53,108241,537,0,1,0,541205.0,36
3460,62,115700,529,0,1,0,578500.0,36
3523,61,109385,468,1,1,0,546925.0,36
4420,58,162202,529,1,1,0,811010.0,36
4720,54,116299,521,2,1,0,581495.0,36

## Tier 5

In [100]:
tier5 = (df['employed'] == 1) & \
        (df['credit_score'].between(550, 750)) & \
        (df['age'].between(35, 50)) & \
        (df['income'].between(60000, 120000)) & \
        (df['existing_loans'].between(1, 3))

In [101]:
df[tier5].shape

(656, 8)

In [102]:
df.loc[tier5, 'loan_amount'] = df.loc[tier5, 'income'] * 6 * \
                                np.round(np.random.uniform(0.9, 1.1, size=df[tier5].shape[0]))

In [103]:
df.loc[tier5, 'loan_amount'] = df.loc[tier5, 'loan_amount'].astype(int)

In [104]:
df[tier5]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
8,36,65670,674,1,1,0,394020.0,36
10,36,66486,609,2,1,0,398916.0,36
12,44,84268,681,2,1,0,505608.0,36
21,39,86326,702,1,1,0,517956.0,36
27,46,77197,749,2,1,1,463182.0,36
...,...,...,...,...,...,...,...,...
4984,48,102284,555,1,1,0,613704.0,36
4986,39,74420,697,1,1,0,446520.0,36
4991,50,81283,651,1,1,0,487698.0,36
4992,40,116169,693,1,1,1,697014.0,36
4995,41,75968,745,2,1,0,455808.0,36

## Tier 6

In [105]:
tier6 = (df['employed'] == 1) & \
        (df['credit_score'].between(550, 700)) & \
        (df['age'].between(30, 45)) & \
        (df['income'].between(40000, 70000)) & \
        (df['existing_loans'].between(1, 2)) & \
        (df["loan_amount"]==0)

In [106]:
df[tier6]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5,39,49276,695,1,1,0,0.0,36
36,44,58536,624,2,1,0,0.0,36
57,38,58615,674,2,1,0,0.0,36
58,45,57903,597,2,1,0,0.0,36
60,36,45629,643,2,1,1,0.0,36
...,...,...,...,...,...,...,...,...
4707,36,43587,643,2,1,1,0.0,36
4753,37,58190,692,2,1,0,0.0,36
4867,41,50824,635,1,1,1,0.0,36
4925,35,47131,677,2,1,0,0.0,36
4934,36,49726,601,1,1,0,0.0,36

In [107]:
df[tier6].shape

(109, 8)

In [108]:
df.loc[(tier6) & (df["loan_amount"]==0)]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5,39,49276,695,1,1,0,0.0,36
36,44,58536,624,2,1,0,0.0,36
57,38,58615,674,2,1,0,0.0,36
58,45,57903,597,2,1,0,0.0,36
60,36,45629,643,2,1,1,0.0,36
...,...,...,...,...,...,...,...,...
4707,36,43587,643,2,1,1,0.0,36
4753,37,58190,692,2,1,0,0.0,36
4867,41,50824,635,1,1,1,0.0,36
4925,35,47131,677,2,1,0,0.0,36
4934,36,49726,601,1,1,0,0.0,36

In [109]:
df.loc[tier6,'loan_amount'] = df.loc[tier6, 'income'] * 4 * \
                                np.round(np.random.uniform(0.9, 1.1, size=df[tier6].shape[0]))

In [110]:
df.loc[tier6, 'loan_amount'] = df.loc[tier6, 'loan_amount'].astype(int)

In [113]:
df[tier6].shape

(109, 8)

In [114]:
df[df["loan_amount"]==0].shape

(4007, 8)

## Tier 7

In [115]:
tier7 = (df['employed'] == 1) & \
        (df['credit_score'] >= 750) & \
        (df['age'] >= 50) & \
        (df['income'] >= 120000) & \
        (df['loan_amount'] == 0)

In [116]:
df[tier7]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
6,60,137459,790,1,1,0,0.0,36
122,58,133286,770,5,1,0,0.0,36
141,57,128478,807,3,1,0,0.0,36
167,64,131239,770,3,1,1,0.0,36
248,63,198484,784,2,1,0,0.0,36
...,...,...,...,...,...,...,...,...
4838,58,197470,778,2,1,0,0.0,36
4856,52,151311,753,0,1,0,0.0,36
4937,56,144512,776,2,1,0,0.0,36
4957,54,141707,771,0,1,0,0.0,36
4997,70,153435,788,2,1,0,0.0,36

In [117]:
df.loc[tier7, 'loan_amount'] = df.loc[tier7, 'income'] * 8 * \
                                np.round(np.random.uniform(0.9, 1.1, size=df[tier7].shape[0]))

In [118]:
df.loc[tier7, 'loan_amount'] = df.loc[tier7, 'loan_amount'].astype(int)

In [128]:
df[tier7]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
6,60,137459,790,1,1,0,1099672.0,36
122,58,133286,770,5,1,0,1066288.0,36
141,57,128478,807,3,1,0,1027824.0,36
167,64,131239,770,3,1,1,1049912.0,36
248,63,198484,784,2,1,0,1587872.0,36
...,...,...,...,...,...,...,...,...
4838,58,197470,778,2,1,0,1579760.0,36
4856,52,151311,753,0,1,0,1210488.0,36
4937,56,144512,776,2,1,0,1156096.0,36
4957,54,141707,771,0,1,0,1133656.0,36
4997,70,153435,788,2,1,0,1227480.0,36

## Tier 8

In [124]:
df[df["loan_amount"]==0].shape

(3882, 8)

In [125]:
unassigned = df[df['loan_amount'] == 0]
print(unassigned[['age', 'income', 'credit_score', 'employed', 'existing_loans']].describe())

# Pattern dekh
print(unassigned['employed'].value_counts())
print(unassigned['credit_score'].describe())

               age         income  credit_score     employed  existing_loans
count  3882.000000    3882.000000   3882.000000  3882.000000     3882.000000
mean     41.299845   88845.377640    704.206079     0.867079        2.046368
std      11.577851   40334.918053     82.511734     0.339533        1.457608
min      25.000000   20246.000000    427.000000     0.000000        0.000000
25%      31.000000   55732.500000    646.000000     1.000000        1.000000
50%      41.000000   81680.000000    706.000000     1.000000        2.000000
75%      50.000000  119525.500000    762.000000     1.000000        3.000000
max      70.000000  199869.000000    900.000000     1.000000        5.000000
employed
1    3366
0     516
Name: count, dtype: int64
count    3882.000000
mean      704.206079
std        82.511734
min       427.000000
25%       646.000000
50%       706.000000
75%       762.000000
max       900.000000
Name: credit_score, dtype: float64

In [126]:
df.to_csv(FILE_PATH, index=False)

In [130]:
df[tier7]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
6,60,137459,790,1,1,0,1099672.0,36
122,58,133286,770,5,1,0,1066288.0,36
141,57,128478,807,3,1,0,1027824.0,36
167,64,131239,770,3,1,1,1049912.0,36
248,63,198484,784,2,1,0,1587872.0,36
...,...,...,...,...,...,...,...,...
4838,58,197470,778,2,1,0,1579760.0,36
4856,52,151311,753,0,1,0,1210488.0,36
4937,56,144512,776,2,1,0,1156096.0,36
4957,54,141707,771,0,1,0,1133656.0,36
4997,70,153435,788,2,1,0,1227480.0,36