In [1]:
print("Hello World")

Hello World

In [43]:
import pandas as pd
import numpy as np

In [44]:
FILE_PATH = "csv/copy.csv"

## Date :- 2026-04-20

In [45]:
df = pd.read_csv(FILE_PATH)

In [46]:
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,151735,616,1,1,0,0,36
1,40,72912,781,1,1,0,0,36
2,49,152455,568,2,0,0,0,36
3,60,120771,654,1,1,1,0,36
4,39,86572,767,1,1,0,0,36

In [6]:
mask = (df["existing_loans"]<1, "default")
df.loc[mask]

35      0
43      0
46      0
63      0
67      0
       ..
4957    0
4959    0
4966    0
4973    0
4998    0
Name: default, Length: 657, dtype: int64

In [7]:
df.loc[
    (df["existing_loans"]==0) &
    (df["default"]>0)
]

Empty DataFrame
Columns: [age, income, credit_score, existing_loans, employed, default]
Index: []

In [8]:
df["loan_amount"] = 0

In [9]:
df.rename(columns={"loan":"loan_amount"}, inplace=True)

In [10]:
tier1 = (df["employed"]==0) & \
(df["credit_score"]<550) & \
(df["age"]<30)

In [11]:
df.loc[tier1]

,age,income,credit_score,existing_loans,employed,default,loan_amount
991,25,4716,513,0,0,0,0
1573,25,3070,539,1,0,0,0
2154,26,4500,546,0,0,0,0
2970,25,3973,519,1,0,1,0
4163,25,3149,536,0,0,0,0
4747,28,4928,513,0,0,0,0

In [12]:
df["loan_tenure_months"] = 36

In [13]:
loan_multiplier = df.loc[tier1, "income"]*2

In [14]:
l = loan_multiplier*np.round(np.random.uniform(0.95, 1.1, size=df[tier1].shape[0]))

In [15]:
df.loc[tier1, "loan_amount"] = l

In [16]:
df.loc[tier1]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
991,25,4716,513,0,0,0,9432,36
1573,25,3070,539,1,0,0,6140,36
2154,26,4500,546,0,0,0,9000,36
2970,25,3973,519,1,0,1,7946,36
4163,25,3149,536,0,0,0,6298,36
4747,28,4928,513,0,0,0,9856,36

## TIER 2

In [17]:
tier2 = (df["employed"]==0) & \
    (df["credit_score"].between(551, 750)) & \
    (df["age"]>=50) & \
    (df["existing_loans"].between(0, 2))

In [18]:
df.loc[
    (df["employed"]==0) &
    (df["credit_score"].between(551, 750)) &
    (df["age"]>=50) & 
    (df["existing_loans"].between(0, 2))
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
67,54,117300,653,0,0,0,0,36
75,51,107442,662,0,0,0,0,36
106,64,58807,738,1,0,0,0,36
118,55,62606,680,2,0,1,0,36
135,60,53703,708,0,0,0,0,36
...,...,...,...,...,...,...,...,...
4857,53,146346,707,2,0,0,0,36
4905,53,125133,685,0,0,0,0,36
4923,58,84989,656,1,0,0,0,36
4970,60,103865,696,1,0,0,0,36
4976,58,198795,695,2,0,1,0,36

In [19]:
df.loc[tier2].shape

(82, 8)

In [20]:
# # High previous earners → high pension
# df.loc[(tier2) & (df['income'] > 100000), 'income'] = np.random.randint(15000, 20000, size=46)

# df.loc[(tier2) & (df['income'].between(50000, 100000)), 'income'] = np.random.randint(8000, 15000, size=35)

# df.loc[(tier2) & (df['income'] < 50000), 'income'] = 6000

In [34]:
df.loc[(tier2) & (df['income'] > 100000)]

In [31]:
df.loc[(tier2) & (df['income'].between(50000, 100000)), "income"] = np.random.randint(8000, 15000, size=35)

In [27]:
df.loc[(tier2) & (df['income'] < 50000), "income"] = 6000

In [33]:
df.loc[(tier2) & (df['income'].between(8000, 15000)) ]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
106,64,8737,738,1,0,0,0,36
118,55,8336,680,2,0,1,0,36
135,60,14495,708,0,0,0,0,36
209,70,11801,705,1,0,1,0,36
296,52,11884,712,2,0,1,0,36
489,52,8191,580,0,0,0,0,36
636,51,10227,647,1,0,0,0,36
773,53,9588,699,2,0,1,0,36
920,54,10677,699,0,0,0,0,36
996,63,14168,654,2,0,0,0,36
1006,52,11867,737,1,0,1,0,36
1166,58,14542,719,1,0,0,0,36
1301,53,8077,745,2,0,0,0,36
1387,60,12010,666,1,0,0,0,36
1548,51,8110,601,0,0,0,0,36
1564,50,14849,705,1,0,1,0,36
1601,58,10615,673,1,0,0,0,36
1783,51,13520,644,2,0,1,0,36
1897,61,9618,746,2,0,0,0,36
2009,53,10981,574,1,0,0,0,36
2050,51,14677,601,2,0,0,0,36
2231,51,13361,673,1,0,1,0,36
2311,63,12730,628,2,0,1,0,36
2929,53,10171,605,2,0,1,0,36
2964,56,10447,659,2,0,1,0,36
3008,54,13258,657,1,0,0,0,36
3180,53,10367,567,2,0,1,0,36
3272,52,12754,742,1,0,1,0,36
3615,50,9167,686,2,0,1,0,36
3734,51,9661,591,1,0,0,0,36
3896,58,8344,598,1,0,0,0,36
3980,58,9377,585,2,0,1,0,36
4283,53,10692,655,1,0,0,0,36
4735,53,13576,675,1,0,0,0,36
4923,58,11475,656,1,0,0,0,36

In [35]:
df.loc[(tier2) & (df['income'] > 100000), 'income'] = np.random.randint(15000, 20000, size=46)

In [47]:
df.loc[(tier2) & (df['income'] > 15000)]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
67,54,15926,653,0,0,0,0,36
75,51,17187,662,0,0,0,0,36
306,57,16613,732,1,0,0,0,36
327,51,15607,728,0,0,0,0,36
494,60,18162,680,0,0,0,0,36
651,55,18184,644,0,0,0,0,36
738,61,16963,652,2,0,0,0,36
884,50,19802,688,2,0,0,0,36
967,63,15041,707,1,0,1,0,36
1155,54,19670,678,2,0,1,0,36
1496,66,15112,669,0,0,0,0,36
1509,59,16983,747,0,0,0,0,36
1951,57,19594,733,2,0,0,0,36
2404,62,18955,664,0,0,0,0,36
2657,52,17205,678,0,0,0,0,36
2709,60,19402,621,0,0,0,0,36
2724,65,17804,677,1,0,1,0,36
2734,65,17279,743,2,0,0,0,36
2814,63,18172,683,1,0,0,0,36
2828,53,16530,676,1,0,1,0,36
3076,51,17598,610,1,0,0,0,36
3178,53,17842,707,2,0,1,0,36
3192,69,16025,614,1,0,0,0,36
3203,57,16339,572,2,0,0,0,36
3213,60,19887,732,0,0,0,0,36
3330,52,19027,627,2,0,0,0,36
3547,59,18708,736,1,0,0,0,36
3564,53,19767,715,1,0,0,0,36
3614,50,19466,583,2,0,0,0,36
3692,56,19196,699,1,0,0,0,36
3941,56,18241,741,1,0,1,0,36
3998,61,18048,706,1,0,1,0,36
4084,57,15623,603,1,0,0,0,36
4226,64,19214,712,1,0,1,0,36
4241,52,18498,725,1,0,1,0,36
4405,52,16438,650,1,0,0,0,36
4583,51,17245,676,2,0,0,0,36
4621,62,15571,706,1,0,0,0,36
4664,50,18527,608,1,0,1,0,36
4768,54,18140,644,2,0,1,0,36
4816,57,18761,601,0,0,0,0,36
4854,56,16166,681,1,0,0,0,36
4857,53,15705,707,2,0,0,0,36
4905,53,15661,685,0,0,0,0,36
4970,60,16573,696,1,0,0,0,36
4976,58,15020,695,2,0,1,0,36

In [41]:
df.to_csv(FILE_PATH, index=False)

In [54]:
df = pd.read_csv(FILE_PATH)

In [62]:
df.loc[tier2, 'loan_amount'] = df.loc[tier2, 'income'] * 7 * np.round(np.random.uniform(0.9, 1.1, size=tier2.sum()))

In [63]:
df.loc[tier2]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
67,54,15926,653,0,0,0,111482,36
75,51,17187,662,0,0,0,120309,36
106,64,8737,738,1,0,0,61159,36
118,55,8336,680,2,0,1,58352,36
135,60,14495,708,0,0,0,101465,36
...,...,...,...,...,...,...,...,...
4857,53,15705,707,2,0,0,109935,36
4905,53,15661,685,0,0,0,109627,36
4923,58,11475,656,1,0,0,80325,36
4970,60,16573,696,1,0,0,116011,36
4976,58,15020,695,2,0,1,105140,36

In [64]:
df.to_csv(FILE_PATH, index=False)